### ISSUE TITLE
Transaction Type for Wallet Transfer

### ISSUE THREAD

**Issue by GEverding** [kinecosystem/kin-python#3]
I'm writing a fn that uses the client to transfer between accounts and it's a `SPEND` or a `EARN`. What is the purpose of the transaction field in a Payment? and Is the the right choice `UNKWONN` if it isn't a `SPEND` or a `EARN`?

**Comment by kikengineering** [comment]
The transaction type field in a payment is for its inclusion in the transaction memo. This value gets used for both KRE calculations as well as for usage metrics. We’ve renamed the 0 value to be NONE in release `0.2.0` for a more explicit non-value that you can use if none of the existing types are relevant for your use case.

If the transfer between accounts you mentioned is between user accounts (e.g. for some user interaction), `P2P` might be the correct choice for you. If not, `NONE` should be used.
