### ISSUE TITLE
Why does `get_balance` returns quarks?

### ISSUE THREAD

**Issue by GEverding** [kinecosystem/kin-python#4]
Why does `get_balance` returns quarks? When I'm making a payment it is in Kin. I don't know of a time I'd want to know what my balance is in quarks? Theres a fn to convert quark to kin but that just seems like extra work that should just happen automatically.

**Comment by kikengineering** [comment]
Thanks for raising this issue - we opted for using quarks where possible (in the client interfaces, APIs, etc.) to avoid issues with rounding/precision loss and for consistency. However, we understand your point that developers will primarily be using Kin throughout the applications.

The alternative we'd propose is using the `Decimal` class from the `decimal` module, and reject any value provided that can’t be represented in an exact number of quarks - does that sound reasonable to you?
