### ISSUE TITLE
client.get_transaction and client.submit_payment are not consistent in Test environment

### ISSUE THREAD

**Issue by watdev2018** [kinecosystem/kin-python#9]
When I submit a payment in Test environment, `client.submit_payment(payment)` it returns a 64 byte transaction hash. When I call `client.get_transaction` with this hash it complains that it should be a 32 byte hash.

There appears to be a consistency issue between `submit_payment` and `get_transaction`. Or am I using the SDK incorrectly? Thank-you!

```
async def send_payment(network, source_private_key, target_public_key, amount):
    environment = Environment.PRODUCTION
    if(network == 'test'):
        environment = Environment.TEST

    client = Client(environment)
    sender = PrivateKey.from_string(source_private_key)
    dest = PublicKey.from_string(target_public_key)
    payment = Payment(sender, dest, TransactionType.EARN,
                      kin_to_quarks(str(amount)))

    tx = client.submit_payment(payment)
    return tx.hex()
```

```
async def get_payment_total_from_transaction(network, tx_id, expected_wallet_address):
    environment = Environment.PRODUCTION
    if(network == 'test'):
        environment = Environment.TEST

    client = Client(environment)

    total_payment = 0

    try:
        transaction_data = client.get_transaction(bytes(tx_id, "utf8"))
    except Exception as e:
        print(e)
        return total_payment

    for payment in transaction_data.payments:
        if payment['dest'] == expected_wallet_address:
            total_payment += quarks_to_kin(payment.quarks)

    return total_payment
```

**Comment by kikengineering** [comment]
Hi there, 

In `get_payment_total_from_transaction`, is `tx_id` the the hexadecimal string form of the ID (i.e. the `tx.hex()` you're returning from `send_payment`)? 

If so, the issue is how you're converting the hexadecimal string `tx_id` back to bytes. Instead of `bytes(tx_id, "utf-8")` you should be doing `bytes.fromhex(tx_id)` to get the raw bytes originally returned from `client.submit_payment`.

**Comment by geoffwhittington** [comment]
Thank-you! I've tried `6c30c7cdcffef3af3410904fa3d56e22ad291ad9e86ae2fda768215f036f5b4c` on the test network and did not trigger the original error.

Unfortunately I'm hitting the following error, but perhaps I should open a different issue for that?

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1606933207.289671704","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
```

**Comment by watdev2018** [comment]
Thank-you! I've tried `6c30c7cdcffef3af3410904fa3d56e22ad291ad9e86ae2fda768215f036f5b4c` on the test network and did not trigger the original error.

Unfortunately I'm hitting the following error, but perhaps I should open a different issue for that?

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1606933207.289671704","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"
```

**Comment by watdev2018** [comment]
Seems to have been resolved with time.
